"""Add HTML fields to run_items table

Revision ID: 357d21170b4c
Revises: 
Create Date: 2026-02-08 22:45:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357d21170b4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_items', sa.Column('raw_html_path', sa.String(), nullable=True))
    op.add_column('run_items', sa.Column('visible_text', sa.Text(), nullable=True))
    op.add_column('run_items', sa.Column('fetch_error', sa.Text(), nullable=True))
    op.add_column('run_items', sa.Column('extract_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_items', 'extract_error')
    op.drop_column('run_items', 'fetch_error')
    op.drop_column('run_items', 'visible_text')
    op.drop_column('run_items', 'raw_html_path')
    # ### end Alembic commands ###